"""예시 문항 전체를 MCQ questions.json으로 변환"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "questions.json"

def mcq(id, category, question, options, correct, choices=None, explanation=""):
    c = choices or len(options)
    return {
        "id": id,
        "type": "mcq",
        "choices": c,
        "category": category,
        "question": question,
        "options": options,
        "correct": correct,
        "explanation": explanation,
    }

questions = []

# ── 공식 Associate 샘플문항 14문항 (네비게이션 도착시간 예측) ──
SAMPLE = "공식 샘플문항"
questions.extend([
    mcq("s01", SAMPLE, "[샘플 1번] scikit-learn 패키지를 import 하는 코드는?",
        ["import sklearn as sk", "import scikit-learn", "from sklearn import *", "pip install sklearn"],
        0, explanation="샘플 1번: sklearn import"),
    mcq("s02", SAMPLE, "[샘플 2번] pandas 패키지를 import 하는 코드는?",
        ["import pandas as pd", "import pandas", "from pd import pandas", "import pd"],
        0, explanation="샘플 2번: pandas import"),
    mcq("s03", SAMPLE, "[샘플 3번] JSON 파일 'A0007IT.json'을 읽어 df에 저장하는 코드는?",
        ["df = pd.read_json('A0007IT.json')", "df = pd.read_csv('A0007IT.json')", "df = json.load('A0007IT.json')", "df = pd.open_json('A0007IT.json')"],
        0, explanation="샘플 3번: read_json, 변수명 df"),
    mcq("s04", SAMPLE, "[샘플 4번] Address1 countplot 후 '-' 지역 행을 삭제하는 처리는?",
        ["df = df[df['Address1'] != '-']", "df.drop('Address1')", "df = df.dropna('Address1')", "df['Address1'] = '-'"],
        0, explanation="countplot: sns.countplot(data=df, x='Address1') 후 필터링"),
    mcq("s05", SAMPLE, "[샘플 4번] Address1 분포를 보여주는 seaborn 그래프는?",
        ["sns.countplot(data=df, x='Address1')", "sns.heatmap(df)", "plt.pie(df['Address1'])", "sns.jointplot(x='Address1')"],
        0, explanation="countplot으로 범주 분포 시각화"),
    mcq("s06", SAMPLE, "[샘플 5번] Time_Driving과 Speed_Per_Hour jointplot 코드는?",
        ["sns.jointplot(data=df, x='Time_Driving', y='Speed_Per_Hour')", "sns.countplot(x='Time_Driving', y='Speed_Per_Hour')", "plt.scatter('Time_Driving', 'Speed_Per_Hour')", "sns.heatmap(Time_Driving, Speed_Per_Hour)"],
        0, explanation="X=실주행시간, Y=평균시속"),
    mcq("s07", SAMPLE, "[샘플 6번] 시속 300 이상 이상치 행 삭제 후 df_temp에 저장하는 코드는?",
        ["df_temp = df[df['Speed_Per_Hour'] < 300]", "df_temp = df.drop('Speed_Per_Hour')", "df_temp = df[df['Speed_Per_Hour'] > 300]", "df_temp = df.dropna()"],
        0, explanation="jointplot에서 이상치 확인 후 조건 필터링"),
    mcq("s08", SAMPLE, "[샘플 7번] df_temp 결측치 확인 후 행 삭제 → df_na 저장은?",
        ["df_na = df_temp.dropna(axis=0)", "df_na = df_temp.fillna(0)", "df_na = df_temp.drop(axis=0)", "df_na = df_temp.isna()"],
        0, explanation="isna().sum() 확인 후 dropna(axis=0)"),
    mcq("s09", SAMPLE, "[샘플 8번] Time_Departure, Time_Arrival 컬럼 삭제 → df_del은?",
        ["df_del = df_na.drop(['Time_Departure','Time_Arrival'], axis=1)", "df_del = df_na.drop(['Time_Departure','Time_Arrival'])", "df_del = df_na.drop(axis=0)", "df_del = df_na.dropna()"],
        0, explanation="컬럼 삭제는 axis=1"),
    mcq("s10", SAMPLE, "[샘플 9번] object 타입 전체 원-핫 인코딩 → df_preset은?",
        ["cols = df_del.select_dtypes('object').columns; df_preset = pd.get_dummies(data=df_del, columns=cols)", "df_preset = pd.get_dummies(df_del)", "df_preset = LabelEncoder(df_del)", "df_preset = df_del.encode()"],
        0, explanation="select_dtypes('object') → get_dummies"),
    mcq("s11", SAMPLE, "[샘플 10번] Time_Driving 예측용 train_test_split (80:20, random_state=42)은?",
        ["x=df_preset.drop('Time_Driving',axis=1); y=df_preset['Time_Driving']; train_test_split(x,y,test_size=0.2,random_state=42)", "train_test_split(df_preset, test_size=0.2)", "train_test_split(Time_Driving, test_size=0.8)", "train_test_split(x, y, train_size=0.2)"],
        0, explanation="label=Time_Driving, test_size=0.2, random_state=42"),
    mcq("s12", SAMPLE, "[샘플 11번] DecisionTreeRegressor(max_depth=5, min_samples_split=3, random_state=120) 학습은?",
        ["dt = DecisionTreeRegressor(max_depth=5, min_samples_split=3, random_state=120); dt.fit(X_train, y_train)", "dt = DecisionTreeRegressor(n_estimators=100); dt.fit(X_train)", "dt = RandomForestRegressor(max_depth=5); dt.fit(X_train, y_train)", "dt.fit(max_depth=5)"],
        0, explanation="파라미터 값을 문제 지시와 동일하게"),
    mcq("s13", SAMPLE, "[샘플 12번] Decision tree MAE 평가 → dt_mae 저장은?",
        ["y_pred=dt.predict(X_valid); dt_mae=mean_absolute_error(y_valid, y_pred)", "dt_mae=dt.score(X_valid, y_valid)", "dt_mae=accuracy_score(y_valid, y_pred)", "dt_mae=dt.predict(X_valid)"],
        0, explanation="predict 후 mean_absolute_error"),
    mcq("s14", SAMPLE, "[샘플 13번] 회귀 DL: Dropout(0.2), loss=mse, epochs=30, batch_size=16 설정은?",
        ["Dropout(0.2); compile(loss='mse'); fit(epochs=30, batch_size=16, validation_data=(X_valid,y_valid))", "Dropout(0.5); loss='mae'; epochs=10", "compile(loss='binary_crossentropy'); epochs=30", "fit(batch_size=32, epochs=50)"],
        0, explanation="회귀=MSE, Dropout 0.2, epochs 30, batch 16"),
    mcq("s15", SAMPLE, "[샘플 14번] 학습/검증 MSE 그래프 (범례 mse, val_mse, 제목 Model MSE)는?",
        ["plt.plot(history.history['mse']); plt.plot(history.history['val_mse']); plt.legend(['mse','val_mse']); plt.title('Model MSE')", "plt.plot(history); plt.title('MSE')", "sns.heatmap(history)", "plt.plot(mse, val_mse)"],
        0, explanation="history.history['mse'], ['val_mse'], 범례·타이틀·축 라벨 확인"),
    # 샘플 변형(유튜브 풀이·다른 샘플 세트에서 자주 나오는 추가 단계)
    mcq("s16", SAMPLE, "[샘플 변형] 수치형 컬럼 상관계수 행렬을 구하는 코드는?",
        ["df.corr()", "df.correlate()", "df.relation()", "np.corr(df)"],
        0, explanation="샘플 4번 변형: corr() 상관관계 분석"),
    mcq("s17", SAMPLE, "[샘플 변형] RobustScaler로 스케일링하는 import는?",
        ["from sklearn.preprocessing import RobustScaler", "from sklearn.preprocessing import MinMaxScaler", "from pandas import RobustScaler", "from keras.preprocessing import RobustScaler"],
        0, explanation="일부 샘플에서 train_test_split 후 RobustScaler 사용"),
    mcq("s18", SAMPLE, "[샘플 변형] 회귀 MSE 성능 평가 함수는?",
        ["mean_squared_error(y_valid, y_pred)", "mean_absolute_error(y_valid, y_pred)", "accuracy_score(y_valid, y_pred)", "r2_score(y_train, y_pred)"],
        0, explanation="MSE vs MAE — 문제 지시 확인"),
    mcq("s19", SAMPLE, "[샘플 변형] RandomForestRegressor로 학습하는 코드는?",
        ["rf = RandomForestRegressor(); rf.fit(X_train, y_train)", "rf = RandomForestClassifier(); rf.fit(X_train, y_train)", "rf = DecisionTreeRegressor(); rf.fit(X_train)", "RandomForestRegressor.predict(X_train)"],
        0, explanation="Regressor=회귀, Classifier=분류"),
    mcq("s20", SAMPLE, "[샘플 변형] 결측치 개수 확인 코드는?",
        ["df.isna().sum()", "df.missing()", "df.count_na()", "df.dropna().sum()"],
        0, explanation="isna().sum() 또는 isnull().sum()"),
])

# ── 연습 문항 뱅크 18문항 ──
BANK = "연습 문항 뱅크"
questions.extend([
    mcq("b01", BANK, "[뱅크 1] numpy, pandas, matplotlib, seaborn import 별칭 조합은?",
        ["np, pd, plt, sns", "numpy, pandas, plot, sea", "n, p, m, s", "arr, df, fig, seaborn"],
        0, explanation="import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns"),
    mcq("b02", BANK, "[뱅크 2] navigation_sample.json → df 저장은?",
        ["df = pd.read_json('navigation_sample.json')", "df = pd.read_csv('navigation_sample.json')", "df = json.read('navigation_sample.json')", "df = pd.load_json('navigation_sample.json')"],
        0, explanation="경로·변수명은 문제 지시 따름"),
    mcq("b03", BANK, "[뱅크 3] df.shape → ans01 저장은?",
        ["ans01 = df.shape", "ans01 = df.size", "ans01 = df.shape()", "ans01 = len(df)"],
        0, explanation="shape는 (행, 열) 튜플"),
    mcq("b04", BANK, "[뱅크 4] 컬럼별 결측치 → ans02는?",
        ["ans02 = df.isna().sum()", "ans02 = df.dropna()", "ans02 = df.isnull()", "ans02 = df.count()"],
        0, explanation="isna().sum()"),
    mcq("b05", BANK, "[뱅크 5] 수치형 상관계수 → corr_matrix는?",
        ["corr_matrix = df.select_dtypes(include='number').corr()", "corr_matrix = df.corr().all()", "corr_matrix = df.describe()", "corr_matrix = np.correlate(df)"],
        0, explanation="수치형 선택 후 corr()"),
    mcq("b06", BANK, "[뱅크 6] Day_Type별 Time_Driving 평균 → df_grp는?",
        ["df_grp = df.groupby('Day_Type')['Time_Driving'].mean()", "df_grp = df.group('Day_Type').mean()", "df_grp = df.pivot('Day_Type', 'Time_Driving')", "df_grp = df.agg('Day_Type')"],
        0, explanation="groupby().mean()"),
    mcq("b07", BANK, "[뱅크 7] Speed≥300 행 제거 → df_temp는?",
        ["df_temp = df[df['Speed'] < 300]", "df_temp = df.drop('Speed')", "df_temp = df[df['Speed'] >= 300]", "df_temp = df.filter(Speed)"],
        0, explanation="이상치 조건 필터링"),
    mcq("b08", BANK, "[뱅크 8] df_temp 결측 행 삭제 → df_na는?",
        ["df_na = df_temp.dropna(axis=0)", "df_na = df_temp.dropna(axis=1)", "df_na = df_temp.fillna(0)", "df_na = df_temp.remove_na()"],
        0, explanation="dropna(axis=0)"),
    mcq("b09", BANK, "[뱅크 9] Time_Departure, Time_Arrival 삭제 → df_del은?",
        ["df_del = df_na.drop(['Time_Departure', 'Time_Arrival'], axis=1)", "df_del = df_na.drop(['Time_Departure', 'Time_Arrival'])", "df_del = df_na.drop(axis=0)", "df_del = df_na.remove(columns=2)"],
        0, explanation="axis=1 컬럼 삭제"),
    mcq("b10", BANK, "[뱅크 10] object 원-핫 → df_preset은?",
        ["cols=df_del.select_dtypes('object').columns; df_preset=pd.get_dummies(data=df_del, columns=cols)", "df_preset=pd.get_dummies(df_del, drop_first=True)", "df_preset=LabelEncoder(df_del)", "df_preset=df_del.encode('object')"],
        0, explanation="get_dummies + object 컬럼"),
    mcq("b11", BANK, "[뱅크 11] 수치형 상관 히트맵 seaborn 함수는?",
        ["sns.heatmap(corr, annot=True)", "sns.countplot(corr)", "sns.jointplot(corr)", "plt.heatmap(corr)"],
        0, explanation="sns.heatmap(..., annot=True)"),
    mcq("b12", BANK, "[뱅크 12] Time_Driving label, 80:20 split, random_state=42는?",
        ["x=df_preset.drop('Time_Driving',axis=1); y=df_preset['Time_Driving']; train_test_split(x,y,test_size=0.2,random_state=42)", "train_test_split(df_preset, 0.2, 42)", "train_test_split(x, y, train_size=0.2)", "split(df_preset, Time_Driving, 0.2)"],
        0, explanation="train_test_split 표준 패턴"),
    mcq("b13", BANK, "[뱅크 13] RandomForestRegressor(100, random_state=42) → pred_y는?",
        ["model=RandomForestRegressor(n_estimators=100,random_state=42); model.fit(X_train,y_train); pred_y=model.predict(X_valid)", "model=RandomForestClassifier(100); pred_y=model.fit()", "pred_y=RandomForestRegressor.predict(X_valid)", "model.fit(); pred_y=model.score()"],
        0, explanation="fit → predict"),
    mcq("b14", BANK, "[뱅크 14] MAE → ans03는?",
        ["ans03 = mean_absolute_error(y_valid, pred_y)", "ans03 = accuracy_score(y_valid, pred_y)", "ans03 = mae(y_valid, pred_y)", "ans03 = mean_absolute_error(pred_y, y_valid)"],
        0, explanation="sklearn.metrics.mean_absolute_error"),
    mcq("b15", BANK, "[뱅크 15] 이진 분류 Sequential (sigmoid + binary_crossentropy)는?",
        ["Dense(1,activation='sigmoid'); compile(loss='binary_crossentropy',metrics=['accuracy'])", "Dense(1,activation='softmax'); compile(loss='mse')", "Dense(10,activation='relu'); compile(loss='categorical')", "compile(optimizer='sgd', loss='mae')"],
        0, explanation="이진: sigmoid + binary_crossentropy"),
    mcq("b16", BANK, "[뱅크 16] contract_type LabelEncoder는?",
        ["le=LabelEncoder(); df['contract_type']=le.fit_transform(df['contract_type'])", "df['contract_type']=get_dummies(df['contract_type'])", "le=LabelEncoder(); le.transform(df)", "LabelEncoder.fit(df['contract_type'])"],
        0, explanation="fit_transform on column"),
    mcq("b17", BANK, "[뱅크 17] monthly_charges MinMaxScaler 0~1은?",
        ["scaler=MinMaxScaler(); df['monthly_charges_scaled']=scaler.fit_transform(df[['monthly_charges']])", "scaler=StandardScaler(); scaler.transform(df)", "MinMaxScaler(df['monthly_charges'])", "df.scale('monthly_charges')"],
        0, explanation="fit_transform with double brackets for single column"),
    mcq("b18", BANK, "[뱅크 18] RandomForestClassifier → ans04 accuracy는?",
        ["clf=RandomForestClassifier(n_estimators=100,random_state=42); clf.fit(X_train,y_train); ans04=accuracy_score(y_valid, clf.predict(X_valid))", "ans04=clf.accuracy()", "ans04=accuracy_score(X_train, y_train)", "clf=RandomForestRegressor(); ans04=clf.score()"],
        0, explanation="Classifier + accuracy_score"),
])

# ── 코드 템플릿 20종 ──
TEMPLATE = "코드 템플릿"
questions.extend([
    mcq("t01", TEMPLATE, "[템플릿] 기본 import 4종은?",
        ["numpy as np, pandas as pd, pyplot as plt, seaborn as sns", "numpy, pandas, matplotlib, seaborn (별칭 없음)", "np, pd만 import", "import all from sklearn"],
        0, explanation="시험 1번 문항 패턴"),
    mcq("t02", TEMPLATE, "[템플릿] CSV/JSON 로딩은?",
        ["pd.read_csv() / pd.read_json()", "pd.load_csv() / pd.load_json()", "open().read_csv()", "csv.read() / json.read()"],
        0, explanation="read_* 패턴"),
    mcq("t03", TEMPLATE, "[템플릿] 데이터 기본 확인 메서드에 없는 것은?",
        ["df.head()", "df.info()", "df.describe()", "df.compile()"],
        3, explanation="head, info, describe, shape, columns, value_counts"),
    mcq("t04", TEMPLATE, "[템플릿] 결측치 확인 코드는?",
        ["df.isna().sum()", "df.missing_count()", "df.null()", "df.dropna().sum()"],
        0, explanation="isna/isnull + sum"),
    mcq("t05", TEMPLATE, "[템플릿] 상관분석 + 히트맵 조합은?",
        ["corr=df.select_dtypes(include='number').corr(); sns.heatmap(corr,annot=True)", "df.corr(); plt.plot()", "sns.countplot(corr)", "heatmap(df.all())"],
        0, explanation="수치형 corr + heatmap"),
    mcq("t06", TEMPLATE, "[템플릿] groupby 집계 예시는?",
        ["df.groupby('컬럼')['타겟'].mean()", "df.group('컬럼').sum()", "df.aggregate(all)", "groupby(df).plot()"],
        0, explanation="mean, sum, count, max, min"),
    mcq("t07", TEMPLATE, "[템플릿] merge vs concat — key로 결합은?",
        ["pd.merge(df1, df2, how='inner', on='key')", "pd.concat(df1, df2, on='key')", "df1.join(df2, key='key')", "pd.combine(df1, df2)"],
        0, explanation="merge=키 결합, concat=행/열 단순 결합"),
    mcq("t08", TEMPLATE, "[템플릿] 이상치 제거 패턴은?",
        ["df_temp = df[df['Speed'] < 300]", "df.drop('Speed')", "df.remove_outliers()", "df.filter(outlier=False)"],
        0, explanation="조건 필터링"),
    mcq("t09", TEMPLATE, "[템플릿] 결측치 평균 대체는?",
        ["df['col'].fillna(df['col'].mean())", "df['col'].dropna()", "df['col'].replace(mean)", "df.fill(0)"],
        0, explanation="fillna(평균) 또는 mode()[0]"),
    mcq("t10", TEMPLATE, "[템플릿] 컬럼 삭제 axis=1 vs inplace=True?",
        ["df_del=df.drop(['col'],axis=1) 또는 df.drop(['col'],axis=1,inplace=True)", "df.drop(axis=0)만 가능", "inplace는 행 삭제 전용", "drop은 inplace 불가"],
        0, explanation="새 변수 vs inplace"),
    mcq("t11", TEMPLATE, "[템플릿] 원-핫 인코딩 표준 패턴은?",
        ["cols=df.select_dtypes('object').columns; pd.get_dummies(data=df, columns=cols)", "pd.one_hot(df)", "LabelEncoder(df)", "df.encode('object')"],
        0, explanation="object 컬럼 → get_dummies"),
    mcq("t12", TEMPLATE, "[템플릿] LabelEncoder import 경로는?",
        ["from sklearn.preprocessing import LabelEncoder", "from pandas import LabelEncoder", "import label_encoder", "from keras.preprocessing import LabelEncoder"],
        0, explanation="sklearn.preprocessing"),
    mcq("t13", TEMPLATE, "[템플릿] MinMaxScaler 결과 범위는?",
        ["0 ~ 1", "-1 ~ 1", "평균 0 표준편차 1", "1 ~ 100"],
        0, explanation="StandardScaler는 평균0·표준편차1"),
    mcq("t14", TEMPLATE, "[템플릿] StandardScaler는?",
        ["평균 0, 표준편차 1로 변환", "0~1 스케일링", "정수 인코딩", "원-핫 인코딩"],
        0, explanation="StandardScaler vs MinMaxScaler"),
    mcq("t15", TEMPLATE, "[템플릿] jointplot 용도는?",
        ["두 수치 변수 분포·관계 동시 시각화", "범주 count", "상관 히트맵", "시계열 플롯"],
        0, explanation="jointplot, boxplot, countplot, heatmap 구분"),
    mcq("t16", TEMPLATE, "[템플릿] train_test_split 기본 비율(자주 출제)은?",
        ["test_size=0.2, random_state=42", "test_size=0.5, random_state=0", "train_size=0.2", "test_size=0.8"],
        0, explanation="80:20 + random_state=42"),
    mcq("t17", TEMPLATE, "[템플릿] ML 4줄 템플릿 순서는?",
        ["모델생성 → fit(X_train,y_train) → predict(X_valid)", "predict → fit → 모델생성", "fit → predict → compile", "evaluate → fit → predict"],
        0, explanation="sklearn: fit → predict"),
    mcq("t18", TEMPLATE, "[템플릿] 회귀 성능 지표 3종은?",
        ["MAE, MSE, R2", "accuracy, f1, precision", "confusion_matrix만", "loss, epochs"],
        0, explanation="mean_absolute_error, mean_squared_error, r2_score"),
    mcq("t19", TEMPLATE, "[템플릿] 분류 성능 지표는?",
        ["accuracy_score, f1_score, confusion_matrix", "MAE, MSE만", "r2_score만", "loss, mse만"],
        0, explanation="분류 vs 회귀 지표 구분"),
    mcq("t20", TEMPLATE, "[템플릿] 다중 분류 DL 출력층은?",
        ["softmax + categorical_crossentropy", "sigmoid + binary_crossentropy", "relu + mse", "linear + accuracy"],
        0, explanation="이진=sigmoid+binary, 다중=softmax+categorical"),
])

# ── 시험 정보·팁 ──
TIP = "시험 팁"
questions.extend([
    mcq("tip01", TIP, "답안 코드 작성 위치는?",
        ["'# 여기에 답안코드를 작성하세요' 셀", "아무 코드 셀", "마크다운 셀", "터미널"],
        0, explanation="지정 셀만 채점"),
    mcq("tip02", TIP, "Associate 합격 점수·시간·문항 수는?",
        ["80점/100, 90분, 14문항", "60점, 60분, 15문항", "70점, 120분, 20문항", "100점, 60분, 10문항"],
        0, explanation="공식 가이드북"),
    mcq("tip03", TIP, "Associate에 없는 것은?",
        ["비정형 데이터(이미지/NLP)", "Tabular 분석", "코드 작성", "시각화"],
        0, explanation="Tabular만, 객목식 이론 없음"),
    mcq("tip04", TIP, "시험 중 참고 가능 사이트는?",
        ["NumPy, Pandas, Matplotlib, Seaborn, sklearn, TensorFlow 문서", "구글 검색 자유", "ChatGPT 사용", "개인 노트"],
        0, explanation="2025 2회부터 6개 공식 문서 링크"),
    mcq("tip05", TIP, "random_state=42를 쓰는 이유는?",
        ["재현 가능한 동일 결과", "속도 향상", "GPU 활성화", "메모리 절약"],
        0, explanation="분할·모델 시드"),
    mcq("tip06", TIP, "Associate 채점 방식은?",
        ["부분점수 없음, 결과 정확 일치", "부분점수 있음", "코드 스타일도 채점", "주석도 채점"],
        0, explanation="변수명·파라미터 정확히"),
    mcq("tip07", TIP, "시험 데이터 로딩은?",
        ["문항과 함께 주어짐, 별도 업로드 불필요할 수 있음", "항상 read_csv 필요", "USB로 가져오기", "인터넷에서 다운"],
        0, explanation="가이드북: 데이터 자동 제공"),
    mcq("tip08", TIP, "회귀 vs 분류 모델 선택 — RandomForestRegressor는?",
        ["연속값 예측(회귀)", "범주 예측(분류)", "클러스터링", "차원 축소"],
        0, explanation="Regressor/Classifier 접미사"),
])

# 절반 정도 5지선다로 보강 (5번째 오답 추가)
EXTRA_WRONG = "위 코드는 모두 틀림 / 해당 없음"
for i, q in enumerate(questions):
    if i % 3 == 0 and len(q["options"]) == 4:
        q["options"] = q["options"] + [EXTRA_WRONG]
        q["choices"] = 5

data = {
    "examTitle": "AICA L2 예시 문항 전체",
    "description": "공식 샘플 14문항 + 연습 뱅크 18문항 + 코드 템플릿 20종 + 시험 팁 (총 66문항)",
    "sources": {
        "공식 샘플문항": sum(1 for q in questions if q["category"] == SAMPLE),
        "연습 문항 뱅크": sum(1 for q in questions if q["category"] == BANK),
        "코드 템플릿": sum(1 for q in questions if q["category"] == TEMPLATE),
        "시험 팁": sum(1 for q in questions if q["category"] == TIP),
    },
    "questions": questions,
}

OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
c4 = sum(1 for q in questions if q["choices"] == 4)
c5 = sum(1 for q in questions if q["choices"] == 5)
print(f"Written {len(questions)} questions ({c4} 4지, {c5} 5지) to {OUT}")
